version: 0.0
os: linux
files:
  - source: .
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: ec2-user

